### ISSUE TITLE
Can Not Register

### ISSUE THREAD

**Issue by krossley** [KamilBugnoKrk/WordTester#2]
Hi,
Thanks for the Blazor sample project.  I have migrated the database to my server and now I'm trying to register and I keep get the message "You need to use reCAPTCHA" I have tried it on Chrome and Edge but both fail to get past the reCAPTCHA.  Any guidance would be appreciated.

**Comment by KamilBugnoKrk** [comment]
Hi,

have you changed the secret for reCAPTCHA for your own value? It should be done in `Authorization/ReCaptcha.cs` file:
` private const string _secret = "<secret>";`

**Comment by krossley** [comment]
I did not.  I will and try it again thanks for the reply.
